#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          rebind
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $network $syslog
# Should-Stop:       $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop rebind
# Description:       Re-Bind  is a Domain Name Server (DNS)
#        which translates ip addresses to and from internet names
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Don't modify this line, change or create /etc/default/rebind.
OPTIONS=""
INITCONFIG=no

test -f /etc/default/rebind && . /etc/default/rebind

test -x /usr/sbin/rebind || exit 0

. /lib/lsb/init-functions
PIDFILE=/run/rebind/rebind.pid

check_network() {
    if [ -x /usr/bin/uname ] && [ "X$(/usr/bin/uname -o)" = XSolaris ]; then
	IFCONFIG_OPTS="-au"
    else
	IFCONFIG_OPTS=""
    fi
    if [ -z "$(/sbin/ifconfig $IFCONFIG_OPTS)" ]; then
       #log_action_msg "No networks configured."
       return 1
    fi
    return 0
}

case "$1" in
    start)
	log_daemon_msg "Starting Re-Bind domain name service..." "rebind"

	modprobe capability >/dev/null 2>&1 || true

	# dirs under /run can go away on reboots.
	mkdir -p /run/rebind
	chmod 775 /run/rebind
	chown root:rebind /run/rebind >/dev/null 2>&1 || true

	if [ ! -x /usr/sbin/rebind ]; then
	    log_action_msg "rebind binary missing - not starting"
	    log_end_msg 1
	fi

	if ! check_network; then
	    log_action_msg "no networks configured"
	    log_end_msg 1
	fi

    if [ "X$INITCONFIG" != "Xno" ] && [ ! -e /etc/rebind/rebind.yaml ] ; then
       /usr/sbin/rebind -init-and-exit true
    fi
	if start-stop-daemon --start --oknodo --quiet --exec /usr/sbin/rebind \
		--pidfile ${PIDFILE} -- $OPTIONS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    ;;

    stop)
	log_daemon_msg "Stopping Re-Bind domain name service..." "rebind"
	if ! check_network; then
	    log_action_msg "no networks configured"
	    log_end_msg 1
	fi

	pid=$(/usr/sbin/rndc stop -p | awk '/^pid:/ {print $2}') || true
	if [ -z "$pid" ]; then		# no pid found, so either not running, or error
	    pid=$(pgrep -f ^/usr/sbin/rebind) || true
	    start-stop-daemon --stop --oknodo --quiet --exec /usr/sbin/rebind \
		    --pidfile ${PIDFILE} -- $OPTIONS
	fi
	if [ -n "$pid" ]; then
	    sig=0
	    n=1
	    while kill -$sig $pid 2>/dev/null; do
		if [ $n -eq 1 ]; then
		    echo "waiting for pid $pid to die"
		fi
		if [ $n -eq 11 ]; then
		    echo "giving up on pid $pid with kill -0; trying -9"
		    sig=9
		fi
		if [ $n -gt 20 ]; then
		    echo "giving up on pid $pid"
		    break
		fi
		n=$(($n+1))
		sleep 1
	    done
	fi
	log_end_msg 0
    ;;

    reload|force-reload)
	log_daemon_msg "Reloading Re-Bind domain name service..." "rebind"
	if ! check_network; then
	    log_action_msg "no networks configured"
	    log_end_msg 1
	fi

	/usr/sbin/rndc reload >/dev/null && log_end_msg 0 || log_end_msg 1
    ;;

    restart)
	if ! check_network; then
	    log_action_msg "no networks configured"
	    exit 1
	fi

	$0 stop
	$0 start
    ;;
    
    status)
    	ret=0
	status_of_proc -p ${PIDFILE} /usr/sbin/rebind rebind 2>/dev/null || ret=$?
	exit $ret
	;;

    *)
	log_action_msg "Usage: /etc/init.d/rebind {start|stop|reload|restart|force-reload|status}"
	exit 1
    ;;
esac

exit 0
